apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: cloudyuga
spec:
  hosts:
  - "*"
  gateways:
  - cloudyuga
  http:
  - route:
    - destination:
        host: cloudyuga-preprod.pre-production.svc.cluster.local
        port:
          number: 80
      weight: 0
    - destination:
        host: cloudyuga-prod.production.svc.cluster.local
        port:
          number: 80
      weight: 100
